package comunicacionObserver;

public enum Operacion {
	NUEVA_RONDA,
	ACTUALIZAR_TABLERO, 
	LANZAMIENTO_DADO,
	MOVIMIENTO,
	CASILLA_ACTIVADA,
	SELECCIONAR_CAMINO, 
	SELECCIONAR_ACCION, 
	PUNTAJES_FINALES, 
	SIN_ACCION, 
	PERDIO_TURNO, 
	BOTON_DADO
}
